const fs = require('fs');

const rawSections = [
  {
    moduleId: 'int-u8',
    data: [
    {q: "1. ¿Qué define principalmente XML en un documento?", o: ["El diseño gráfico", "La estructura y la información", "El comportamiento en el navegador", "La base de datos asociada"], a: "La estructura y la información", f: "XML se centra en organizar los datos mediante una estructura jerárquica, separando el contenido de su presentación."},
    {q: "2. ¿Cuál de estas características es propia de XML?", o: ["No es independiente de plataforma", "Mezcla diseño y contenido", "Es estándar para intercambio de información estructurada", "Solo para navegadores antiguos"], a: "Es estándar", f: "XML es un estándar universal e independiente de la plataforma para el intercambio de datos."},
    {q: "3. En el fragmento '<agenda><contacto><nombre>Javier</nombre></contacto></agenda>', ¿cuál es la etiqueta raíz?", o: ["contacto", "nombre", "Javier", "agenda"], a: "agenda", f: "La etiqueta raíz es el elemento que envuelve a todos los demás en el documento."},
    {q: "4. En XML, ¿qué elemento define información extra como 'tipo=\"móvil\"' en un teléfono?", o: ["Comentario", "Entidad", "Atributo", "Namespace"], a: "Atributo", f: "Los atributos proporcionan información adicional sobre los elementos dentro de la etiqueta de apertura."},
    {q: "5. ¿Qué diferencia clave hay entre HTML y XML?", o: ["HTML es estructural y XML visual", "XML define estructura; HTML mezcla contenido y formato", "HTML es siempre bien formado", "XML no usa etiquetas"], a: "XML define estructura", f: "XML es puramente estructural y semántico, mientras que HTML incluye etiquetas de formato visual (como <b> o <i>)."},
    {q: "6. ¿Cuál de las siguientes reglas corresponde a un documento XML bien formado?", o: ["No necesita elemento raíz", "Etiquetas de cierre opcionales", "Anidamiento debe respetar la estructura de árbol", "Atributos sin comillas"], a: "Anidamiento debe respetar la estructura de árbol", f: "Un XML bien formado debe tener una única raíz y las etiquetas deben cerrarse en el orden inverso al que se abrieron."},
    {q: "7. En '<teléfono tipo=\"móvil\">637059874</teléfono>', ¿qué valor tiene el atributo tipo?", o: ["teléfono", "móvil", "637059874", "tipo"], a: "móvil", f: "El valor del atributo es la cadena de texto encerrada entre las comillas."},
    {q: "8. ¿Cuál de estas restricciones de nombres de etiquetas es correcta en XML?", o: ["Pueden empezar por número", "Pueden contener espacios", "No pueden empezar por 'XML'", "Cualquier símbolo al inicio"], a: "No pueden empezar por 'XML'", f: "Los nombres en XML tienen reglas: no pueden empezar por números, ni por la cadena 'xml' (en cualquier combinación de mayúsculas)."},
    {q: "9. En el fragmento '<birds><owl>Bubo bubo</owl></birds>', ¿qué representa owl?", o: ["Etiqueta raíz", "Atributo", "Hija de birds", "Comentario"], a: "Hija de birds", f: "owl está anidado dentro de birds, por lo tanto es un elemento hijo."},
    {q: "10. En interfaces con XML, 'mapear la interfaz' significa:", o: ["Convertir XML en CSS", "Traducir XML a código o elementos de la plataforma", "Convertir HTML en XML", "Compactar archivo"], a: "Traducir", f: "Consiste en que el motor de la interfaz lea el XML y cree los objetos reales (botones, paneles) del sistema operativo."},
    {q: "11. Una ventaja de usar lenguajes XML para interfaces es:", o: ["Obliga a un único lenguaje", "Impide trabajar en paralelo", "Permite separar interfaz y funcionalidad", "Solo sirve en web"], a: "Permite separar", f: "Diseñadores y programadores pueden trabajar de forma independiente."},
    {q: "12. XUL se utiliza principalmente para:", o: ["Consola", "Interfaces de Mozilla/Firefox", "Sistemas embebidos", "Bases de datos"], a: "Interfaces de Mozilla/Firefox", f: "XML User Interface Language (XUL) fue creado para el ecosistema de aplicaciones de Mozilla."},
    {q: "13. XUL se apoya en otras tecnologías como:", o: ["CSS y JavaScript", "PHP y SQL", "COBOL y Fortran", "Bash y sed"], a: "CSS y JavaScript", f: "Utiliza CSS para el aspecto visual y JavaScript para el comportamiento."},
    {q: "14. XAML se usa en el contexto de:", o: ["Java SE", ".NET Framework y Windows", "Android nativo", "Web PHP"], a: ".NET Framework", f: "XAML es el lenguaje de Microsoft para definir interfaces en WPF, UWP y Xamarin."},
    {q: "15. En XAML '<Button Content=\"Aceptar\" />', ¿qué atributo fija el texto visible?", o: ["Width", "Background", "Content", "Button"], a: "Content", f: "En XAML, la propiedad 'Content' define lo que el control muestra en su interior."},
    {q: "16. La etiqueta raíz en XAML debe cumplir que:", o: ["Puede no cerrarse", "Varias raíces", "Cerrada y única", "Sin atributos"], a: "Cerrada y única", f: "Como cualquier XML, XAML requiere un único elemento raíz que contenga al resto."},
    {q: "17. ¿Qué control XAML organiza verticalmente otros controles?", o: ["Grid", "Canvas", "StackPanel", "Border"], a: "StackPanel", f: "StackPanel apila sus elementos hijos en una sola línea (vertical u horizontal)."},
    {q: "18. ¿Qué característica comparten XAML, XUL y XIML?", o: ["Binarios propietarios", "Basados en XML", "No sirven para interfaces", "Solo lógica"], a: "Basados en XML", f: "Todos heredan la sintaxis y reglas del estándar XML."},
    {q: "19. XIML se orienta a:", o: ["Maquetación de formularios", "Bases de datos", "Todo el ciclo de vida de la interfaz", "Reemplazar HTML"], a: "Todo el ciclo de vida de la interfaz", f: "Es un lenguaje más abstracto que busca gestionar todo el ciclo vital de la UI."},
    {q: "20. ¿Qué ventaja tiene SVG frente a mapas de bits?", o: ["Menos espacio siempre", "No se escala", "Vectorial y redimensionable sin perder calidad", "No usa XML"], a: "Vectorial y redimensionable", f: "Al ser fórmulas matemáticas expresadas en XML, no se pixelan al agrandarse."},
    {q: "21. Un fichero FXML generado por Scene Builder sirve para:", o: ["Describir interfaz JavaFX", "Guardar datos", "Consultas SQL", "Compilar bytecode"], a: "Describir interfaz JavaFX", f: "FXML es el formato que usa JavaFX para separar la vista del controlador."},
    {q: "22. En interfaces con XML, ¿qué beneficio da la división del trabajo?", o: ["Dificulta comunicación", "Interfaz y lógica por equipos distintos", "Menos herramientas", "Reduce pruebas"], a: "Interfaz y lógica por equipos distintos", f: "Optimiza los tiempos de desarrollo al permitir tareas simultáneas."},
    {q: "23. ¿Dónde se define el diseño visual final (colores, fuentes) en XML?", o: ["Atributos de texto", "Hojas de estilo o archivos de diseño", "Etiqueta raíz", "No se define"], a: "Hojas de estilo o archivos de diseño", f: "Se sigue el principio de separación de preocupaciones (separación de diseño y estructura)."},
    {q: "24. En XUL, ¿qué se usa para el comportamiento dinámico?", o: ["SQL", "JavaScript", "Python", "Bash"], a: "JavaScript", f: "JavaScript gestiona los eventos y la lógica del lado del cliente en XUL."},
    {q: "25. En XAML, ¿cómo se relacionan las etiquetas con .NET?", o: ["Independientes", "Cada elemento mapea a una clase .NET", "Comentarios", "Compilan a C++"], a: "Cada elemento mapea a una clase .NET", f: "Un elemento <Button> en XAML instancia una clase System.Windows.Controls.Button."},
    {q: "26. ¿Qué tecnología sirve para describir RIAs (Interfaces Ricas)?", o: ["Flex de Adobe", "Fortran", "COBOL", "Shell Script"], a: "Flex de Adobe", f: "Adobe Flex (usando MXML) fue pionero en interfaces ricas basadas en XML."},
    {q: "27. En XML, ¿qué ocurre con '<a><b></a></b>'?", o: ["Válido", "Correcto navegador", "Mal formado (anidamiento incorrecto)", "Warning"], a: "Mal formado", f: "Las etiquetas deben cerrarse en orden inverso (LIFO)."},
    {q: "28. En XAML, ¿qué control muestra texto simple sin interacción?", o: ["Button", "ToggleButton", "TextBlock", "Slider"], a: "TextBlock", f: "TextBlock es el control básico para mostrar texto estático."},
    {q: "29. Un toolkit de herramientas como Scene Builder incluye:", o: ["Solo BD", "Menús, botones, etiquetas y campos", "Solo 3D", "Scripts compilación"], a: "Menús, botones, etiquetas y campos", f: "Proporciona la paleta de componentes estándar para construir la UI."},
    {q: "30. Al 'conectar' la interfaz XML a la app, es necesario:", o: ["Traducir XML a la plataforma final", "Reescribir en C", "Desactivar eventos", "Quitar atributos"], a: "Traducir XML a la plataforma final", f: "Es el proceso de 'inflado' o renderizado de la interfaz."},
    {q: "31. ¿Qué es un informe?", o: ["Listado sin formato", "Documento que muestra contenido de datos formateado", "Copia seguridad BD", "Manual usuario"], a: "Documento que muestra", f: "Un informe organiza datos brutos para convertirlos en conocimiento legible."},
    {q: "32. ¿Razón para usar informes en un negocio?", o: ["Aumentar ejecutable", "Controlar distribución al imprimir", "Evitar ver datos", "Reducir tablas"], a: "Controlar distribución", f: "Los informes aseguran que la información impresa tenga el formato y rigor necesarios."},
    {q: "33. En informes, la fase de diseño consiste en:", o: ["Conectar sin plantillas", "Determinar distribución con herramienta gráfica", "Solo filtros", "Exportar PDF"], a: "Determinar distribución con herramienta gráfica", f: "Es la maquetación visual de dónde irá cada dato (JasperSoft Studio)."},
    {q: "34. Un informe incrustado se caracteriza por:", o: ["Servidor externo", "Solo navegador", "Compilado dentro del ensamblado", "Sin clases"], a: "Compilado", f: "Forma parte del paquete de la aplicación (recurso interno)."},
    {q: "35. Herramienta de informes de SAP:", o: ["JasperReports", "Eclipse BIRT", "Crystal Reports", "Power BI"], a: "Crystal Reports", f: "Crystal Reports es la solución histórica de SAP para informes de gestión."},
    {q: "36. JasperReports utiliza como plantilla de diseño:", o: [".pdf", ".jrxml", ".docx", ".xls"], a: ".jrxml", f: "El archivo JRXML es el XML de diseño que luego se compila a .jasper."},
    {q: "37. Flujo de JasperReports:", o: ["Datos->PDF->JRXML", "JRXML->JasperPrint->BBDD", "JRXML->compilación .jasper->llenado->exportación", "HTML->JRXML->PDF"], a: "compilación", f: "Es el ciclo de vida estándar del motor Jasper."},
    {q: "38. ¿Papel de los parámetros en un informe?", o: ["Cálculos internos", "Estructura fija", "Diferentes resultados según valores en ejecución", "Solo paginar"], a: "Diferentes resultados según valores en ejecución", f: "Se usan para filtrar el informe dinámicamente (ej: pasar una fecha)."},
    {q: "39. Propiedad de parámetro que indica su clase (valor que recibirá):", o: ["Default Value", "Use as prompt", "Name", "Parameter class"], a: "Parameter class", f: "Define si el parámetro es un String, Integer, Date, etc."},
    {q: "40. Diferencia principal entre parámetros y variables:", o: ["Numérico vs Texto", "Parámetros constantes", "Variables cambian durante creación; parámetros desde fuera", "Sinónimos"], a: "Variables cambian", f: "Los parámetros son entradas externas; las variables son cálculos internos (sumas, conteos)."},
    {q: "41. ¿Nombre de cada zona horizontal del informe?", o: ["Campo", "Banda", "Segmento", "Grupo"], a: "Banda", f: "JasperReports divide el informe en bandas (Title, Detail, Footer, etc.)."},
    {q: "42. Sección para información resumida del detalle:", o: ["Page Header", "Column Header", "Summary", "Detail"], a: "Summary", f: "La banda 'Summary' aparece al final del informe para totales generales."},
    {q: "43. Objetivo de agrupar datos:", o: ["Reducir tamaño", "Velocidad compilación", "Organizar por cambios en expresión", "Eliminar pies"], a: "Organizar por cambios", f: "Permite ver, por ejemplo, las ventas 'agrupadas' por ciudad."},
    {q: "44. Requisito para iniciar el ciclo de vida del informe:", o: ["Formato exportación", "Origen de datos válido", "Desplegar producción", "Logotipo"], a: "Origen", f: "Sin datos (SQL, XML, Java Objects) el informe no puede rellenarse."},
    {q: "45. Operación que muestra solo información relevante:", o: ["Paginación", "Filtrado", "Agrupamiento", "Sumarios"], a: "Filtrado", f: "El filtrado limita el número de registros que se procesan y muestran."}
    ]
  },
  {
    moduleId: 'int-u9',
    data: [
    {q: "1. Un componente se define, según el tema, por:", o: ["Solo por su aspecto visual", "Estado, comportamiento e interfaz", "Únicamente por sus eventos", "Solo por su empaquetado"], a: "Estado", f: "Un componente es una unidad de software independiente que encapsula datos y funcionalidad accesible mediante una interfaz clara."},
    {q: "2. ¿Cuál de estas características NO es requisito de un componente?", o: ["Adaptabilidad", "Persistencia", "Introspección", "Necesariamente heredar de JFrame"], a: "necesariamente", f: "Los componentes pueden ser de muchos tipos; heredar de JFrame no es una condición para ser un componente."},
    {q: "3. En Java, un getter típico para una propiedad de tipo String se define como:", o: ["public void getNombre(String n)", "public String getNombre()", "public getNombre()", "String setNombre()"], a: "public String getNombre()", f: "Un getter devuelve el valor de la propiedad y no recibe parámetros."},
    {q: "4. En Java, un setter típico para una propiedad int se define como:", o: ["public void setEdad(int edad)", "public int setEdad()", "void getEdad(int edad)", "public int edad()"], a: "public void setEdad(int edad)", f: "Un setter recibe el nuevo valor como parámetro y normalmente no devuelve nada (void)."},
    {q: "5. Para una propiedad booleana, el getter recomendado es:", o: ["public boolean getActivo()", "boolean setActivo()", "public void isActivo()", "public boolean isActivo()"], a: "public boolean isActivo()", f: "La convención JavaBeans indica que las propiedades booleanas deben usar el prefijo 'is'."},
    {q: "6. Si una propiedad solo tiene método get y no set, ¿qué tipo de propiedad es?", o: ["De solo escritura", "De solo lectura", "Indexada", "Restringida"], a: "De solo lectura", f: "Al no tener setter, el valor no puede modificarse desde fuera del componente."},
    {q: "7. Las propiedades indexadas se utilizan cuando:", o: ["Solo hay un único valor", "El número de elementos es fijo", "Se desconoce a priori el número de elementos", "No se necesita acceso por índice"], a: "Se desconoce a priori el número de elementos", f: "Permiten gestionar colecciones de datos donde el acceso se realiza mediante un índice entero."},
    {q: "8. ¿Qué métodos se usan para gestionar oyentes en propiedades compartidas (bound)?", o: ["addMouseListener", "addPropertyChangeListener / removePropertyChangeListener", "addActionListener", "addKeyListener"], a: "addPropertyChangeListener", f: "Las propiedades bound notifican cambios a los objetos interesados mediante estos métodos."},
    {q: "9. ¿Qué interface deben implementar los objetos que escuchan cambios en propiedades compartidas?", o: ["Cloneable", "Serializable", "PropertyChangeListener", "Runnable"], a: "PropertyChangeListener", f: "Es la interfaz estándar que define el método propertyChange()."},
    {q: "10. En propiedades restringidas, los oyentes pueden:", o: ["Ignorar todos los cambios", "Vetar el cambio de valor", "Cambiar el tipo de dato", "Eliminar la propiedad"], a: "Vetar el cambio de valor", f: "Lanzan una PropertyVetoException si el nuevo valor no es aceptable."},
    {q: "11. ¿Qué interfaz se usa para escuchar propiedades restringidas?", o: ["VetoableChangeListener", "PropertyChangeListener", "MouseListener", "ActionListener"], a: "VetoableChangeListener", f: "Es la interfaz específica para manejar cambios que pueden ser rechazados."},
    {q: "12. Un editor de propiedades sirve para:", o: ["Compilar código Java", "Modificar visualmente los valores de las propiedades en tiempo de diseño", "Enviar eventos de ratón", "Generar bases de datos"], a: "Modificar visualmente", f: "Permite al desarrollador configurar el componente desde el IDE sin escribir código."},
    {q: "13. En JavaScript, al ejecutar 'p.nombre = \"Ana\";', ¿qué método se llama?", o: ["constructor", "get nombre()", "set nombre(String)", "set nombre(nuevoNombre)"], a: "set nombre", f: "La asignación activa automáticamente el método 'set' definido para esa propiedad."},
    {q: "14. La introspección permite que el IDE:", o: ["Ignore los getters y setters", "Reconozca dinámicamente métodos, propiedades y eventos", "Solo vea métodos privados", "Cambie nombres automáticamente"], a: "Reconozca dinámicamente", f: "El IDE 'mira' dentro de la clase para saber qué se puede configurar visualmente."},
    {q: "15. La reflexión busca, entre otros, métodos públicos que empiezan por:", o: ["do o run", "on o handle", "get o set", "print o show"], a: "get o set", f: "Usa patrones de diseño para identificar propiedades por sus prefijos."},
    {q: "16. La persistencia de un componente consiste en:", o: ["Guardar su estado para recuperarlo después", "Mantenerlo siempre en pantalla", "Evitar que genere eventos", "Borrar sus propiedades"], a: "Guardar su estado", f: "Permite que el componente 'sobreviva' al cierre de la aplicación guardando sus valores."},
    {q: "17. En Java, para serialización automática se requiere:", o: ["Implementar Runnable", "Implementar Serializable y tener constructor sin argumentos", "Implementar ActionListener", "No declarar atributos"], a: "Implementar Serializable", f: "La interfaz Serializable permite el volcado de memoria y el constructor vacío es necesario."},
    {q: "18. En serialización manual (Externalizable) se deben implementar:", o: ["readObject y writeObject", "save y load", "readExternal y writeExternal", "serialize y deserialize"], a: "readExternal y writeExternal", f: "Dan control total al desarrollador sobre qué y cómo se escribe/lee el estado."},
    {q: "19. ¿Qué campos se excluyen de la serialización automática en Java?", o: ["private", "protected", "static y transient", "final"], a: "static y transient", f: "Static pertenece a la clase y transient se usa específicamente para marcar campos que no deben guardarse."},
    {q: "20. En el diagrama de eventos, la 'fuente del evento' es:", o: ["El IDE", "El componente que genera el evento", "El sistema operativo", "El compilador"], a: "El componente que genera el evento", f: "Es el objeto que detecta la interacción y notifica a los oyentes."},
    {q: "21. En el manejo de eventos personalizados, uno de los pasos es:", o: ["Crear una clase para los eventos que se lancen", "Eliminar todos los oyentes", "Desactivar la serialización", "Quitar todas las propiedades"], a: "Crear una clase", f: "La clase de evento suele heredar de java.util.EventObject."},
    {q: "22. Además de la clase de evento, ¿qué necesitas para disparar 'CambioTextoEvent'?", o: ["Un método main", "Una interfaz oyente (CambioTextoListener)", "Un hilo dedicado", "Un archivo XML"], a: "Una interfaz oyente", f: "Define el contrato que deben cumplir los objetos que quieran escuchar el evento."},
    {q: "23. En JavaBeans, ¿qué interfaz debe implementar una clase para ser componente reutilizable?", o: ["ActionListener", "Cloneable", "Runnable", "Serializable"], a: "Serializable", f: "Es fundamental para que el IDE pueda guardar el estado configurado en tiempo de diseño."},
    {q: "24. El empaquetado de componentes JavaBeans suele hacerse en:", o: ["Archivos .class individuales", "Archivos .jar que incluyen recursos y BeanInfo", "Archivos .exe", "Scripts .sh"], a: "Archivos .jar", f: "El JAR encapsula todo lo necesario para que el componente funcione en cualquier IDE."},
    {q: "25. Un fichero de manifiesto (.mf) sirve para:", o: ["Guardar la base de datos", "Describir contenido e indicar qué clases son JavaBeans", "Registrar usuarios", "Almacenar recursos gráficos"], a: "Describir contenido", f: "Informa al IDE qué clase dentro del JAR debe ser tratada como un componente visual."},
    {q: "26. En XAML '<Slider Minimum=\"0\" Maximum=\"100\" Value=\"50\" />', ¿qué propiedad es el estado actual?", o: ["Minimum", "Maximum", "Value", "Width"], a: "Value", f: "Representa el dato dinámico que el control está manejando en ese instante."},
    {q: "27. En Flutter o React, el 'estado' corresponde con:", o: ["Sus métodos estáticos", "Sus propiedades que cambian y afectan a la interfaz", "Sus clases internas", "Sus archivos de recursos"], a: "Sus propiedades que cambian y afectan a la interfaz", f: "Cuando el estado cambia, el componente se redibuja automáticamente."},
    {q: "28. ¿Ventaja principal del desarrollo basado en componentes?", o: ["Más sencillo, rápido y reduce errores", "Aumenta coste y tiempo", "Solo para proyectos pequeños", "Evita el uso de IDEs"], a: "Más sencillo, rápido y reduce errores", f: "La reutilización de piezas ya probadas agiliza enormemente el desarrollo."},
    {q: "29. ¿Qué requiere un componente para responder a acciones del usuario?", o: ["Un archivo JSON", "Gestión de eventos", "Persistencia", "Serialización Externalizable"], a: "Gestión de eventos", f: "Sin eventos, el componente no puede comunicar que algo ha sucedido (clic, cambio de texto)."},
    {q: "30. Gracias a la introspección, la ventana de propiedades puede:", o: ["Mostrar dinámicamente las propiedades para editarlas", "Ejecutar el programa", "Gestionar bases de datos", "Generar código SQL"], a: "Mostrar dinámicamente las propiedades", f: "Extrae los nombres de las propiedades analizando los métodos get/set."},
    {q: "31. ¿Cuál es el propósito principal de las pruebas de software?", o: ["Demostrar que no hay ningún error", "Encontrar la mayor cantidad posible de errores para minimizarlos", "Reducir tiempo eliminando etapas", "Reemplazar documentación"], a: "Encontrar la mayor cantidad", f: "Las pruebas buscan fallos para aumentar la fiabilidad del producto antes de la entrega."},
    {q: "32. ¿Qué afirmación sobre la calidad es correcta?", o: ["Solo al final", "Solo rapidez", "Forma de pensar y actuar en todas las fases", "Sin relación con el cliente"], a: "Forma de pensar", f: "La calidad se asegura desde la toma de requisitos hasta el despliegue."},
    {q: "33. ¿Diferencia básica entre verificación y validación?", o: ["Verificación usuario / Validación desarrollador", "Son lo mismo", "Verificación opcional", "Verificación: cumple especificaciones / Validación: cumple expectativas usuario"], a: "Verificación: cumple especificaciones", f: "Verificación: ¿Hacemos el producto correctamente? / Validación: ¿Hacemos el producto correcto?"},
    {q: "34. ¿En qué consisten las pruebas unitarias?", o: ["Probar app completa como caja negra", "Evaluar módulos o clases por separado", "Verificar requisitos no funcionales", "Simular cargas extremas"], a: "Evaluar módulos o clases", f: "Se centran en la unidad mínima de código (clase o método)."},
    {q: "35. ¿Cuándo se realizan las pruebas de integración?", o: ["Antes de las unitarias", "Después de producción", "Tras probar individualmente los módulos", "Solo en ágil"], a: "Tras probar", f: "Buscan detectar fallos en la comunicación y ensamblaje de las unidades."},
    {q: "36. En la integración ascendente (Bottom-Up) se comienza por:", o: ["El programa principal", "Módulos de bajo nivel hasta el principal", "Módulos intermedios", "Capa de interfaz"], a: "Módulos de bajo nivel", f: "Se prueban primero los componentes base que no dependen de otros."},
    {q: "37. ¿Qué describen las pruebas de sistema?", o: ["Comportamiento conjunto (seguridad, velocidad, fiabilidad)", "Solo interfaz gráfica", "Solo base de datos", "Sustituyen integración"], a: "Comportamiento conjunto", f: "Prueban el software como un todo en un entorno similar al real."},
    {q: "38. Las pruebas de regresión tienen como objetivo:", o: ["Acelerar compilación", "Verificar que cambios no introdujeron efectos colaterales", "Reducir casos de prueba", "Saltarse unitarias"], a: "Verificar que cambios", f: "Aseguran que al arreglar un fallo no hemos roto algo que ya funcionaba."},
    {q: "39. Pruebas de capacidad que someten al sistema a cargas anormales:", o: ["Alfa", "Humo", "Resistencia o estrés", "Aceptación"], a: "Resistencia", f: "Buscan el punto de ruptura o degradación del sistema ante tráfico masivo."},
    {q: "40. ¿Qué se evalúa en las pruebas de recuperación?", o: ["Diseño de interfaz", "Recuperación correcta tras un fallo", "Tiempo bajo carga normal", "Compatibilidad SO"], a: "Recuperación correcta", f: "Verifican la capacidad de restaurar datos y servicio tras un incidente."},
    {q: "41. ¿Cuál es el objetivo de las pruebas de seguridad?", o: ["Aumentar usabilidad", "Probar solo autenticación", "Reducir memoria", "Verificar protección contra accesos no autorizados"], a: "Verificar protección", f: "Buscan vulnerabilidades y debilidades en el control de acceso y datos."},
    {q: "42. ¿Qué es la prueba de usuario o de usabilidad?", o: ["Interfaz amigable, intuitiva y funcional", "Rendimiento automatizado", "Exclusiva seguridad", "Solo validar BD"], a: "Interfaz amigable", f: "Se centra en la interacción humana y facilidad de aprendizaje."},
    {q: "43. ¿Qué indican las limitaciones respecto al conjunto de casos de prueba?", o: ["Cubrir todos siempre", "Conjunto teóricamente infinito", "Basta una prueba", "No aportan info"], a: "Conjunto teóricamente infinito", f: "Debido a esto, se seleccionan subconjuntos representativos para probar."},
    {q: "44. ¿Qué porcentaje del coste total suele representar la fase de pruebas?", o: ["5–10%", "15–20%", "40–50%", "Más del 90%"], a: "40", f: "Es una de las fases más costosas y críticas para el éxito del proyecto."},
    {q: "45. ¿Qué pruebas realiza el cliente en su entorno sin el desarrollador?", o: ["Alfa", "Beta", "Unitarias", "Humo"], a: "Beta", f: "Son pruebas de campo con usuarios reales fuera del laboratorio de desarrollo."}
    ]
  },
  {
    moduleId: 'int-u10',
    data: [
    {q: "1. ¿Qué interfaz se suele crear primero en NetBeans/Eclipse al empezar una app de escritorio sin lógica?", o: ["Base de datos MySQL", "Ventana visual básica", "Informe Jasper PDF", "Prueba JUnit"], a: "Ventana visual básica", f: "Se empieza por el prototipo visual o ventana principal (JFrame) para definir la disposición de elementos."},
    {q: "2. ¿Qué biblioteca de Java se utiliza habitualmente para JFrame, JDialog y JTable?", o: ["Swing", "JavaFX", "WPF", "AWT"], a: "Swing", f: "Swing es la biblioteca estándar más común para interfaces de escritorio en Java."},
    {q: "3. En la tabla 'nota', ¿qué campo es el identificador principal INT, clave primaria y autoincremental?", o: ["titulo", "contenido", "fecha_creacion", "id"], a: "id", f: "El campo 'id' se utiliza universalmente como Primary Key autoincremental en bases de datos relacionales."},
    {q: "4. ¿Qué clase gestiona las conexiones JDBC con MySQL en nuestros proyectos?", o: ["ConexionBD", "Nota", "NotaDAO", "FrmPrincipal"], a: "ConexionBD", f: "Esta clase encapsula la configuración del Driver, URL, usuario y contraseña de la base de datos."},
    {q: "5. ¿Qué métodos mínimos debe incluir NotaDAO para operaciones CRUD?", o: ["Solo listar", "Listar/buscar/insertar/actualizar/borrar", "Solo borrar", "Ninguno"], a: "Listar/buscar/insertar/actualizar/borrar", f: "CRUD significa Create, Read, Update, Delete; el DAO debe cubrir todas esas acciones."},
    {q: "6. ¿Qué componente Swing organiza registros en columnas como ID, Título y Fecha?", o: ["JList", "JTable", "JTextArea", "JTree"], a: "JTable", f: "JTable es el componente idóneo para representar datos tabulares."},
    {q: "7. ¿Qué dependencia de Maven se usa para conectar Java con MySQL?", o: ["mysql-connector-java", "jasperreports", "scenebuilder", "hibernate-core"], a: "mysql-connector-java", f: "Es el driver oficial que permite la comunicación JDBC con el servidor MySQL."},
    {q: "8. ¿Qué herramienta diseña e integra visualmente interfaces JavaFX?", o: ["JasperSoft", "Scene Builder", "NetBeans Matisse", "Gluon Scene"], a: "Scene Builder", f: "Es la herramienta visual externa que genera archivos FXML para JavaFX."},
    {q: "9. ¿Qué lenguaje de marcado utiliza WPF para definir la interfaz?", o: ["HTML/CSS", "JSON", "XAML", "YAML"], a: "XAML", f: "XAML es el lenguaje basado en XML de Microsoft para interfaces en .NET/WPF."},
    {q: "10. ¿Qué significa usabilidad relacionada con utilidad y accesibilidad?", o: ["Rendimiento", "Escalabilidad", "Mantenibilidad", "Facilidad de uso práctica"], a: "Facilidad de uso práctica", f: "La usabilidad mide qué tan fácil resulta para un usuario alcanzar sus objetivos con el software."},
    {q: "11. ¿Cuáles son los 5 atributos clásicos de usabilidad?", o: ["Velocidad/memoria", "Aprender/eficaz/errores/feliz/recordar", "Colores/fuentes", "MVC/MVP"], a: "Aprender/eficaz/errores/feliz/recordar", f: "Se basan en los principios de Nielsen: Facilidad de aprendizaje, Eficiencia, Memorabilidad, Errores y Satisfacción."},
    {q: "12. ¿Qué mide el tiempo medio para completar tareas en pruebas?", o: ["Código", "Peso JAR", "Usabilidad", "Clases"], a: "Usabilidad", f: "El tiempo por tarea es una métrica directa de la eficiencia de la interfaz."},
    {q: "13. ¿Qué debe hacerse con un login en Swing mal diseñado?", o: ["Dejarlo", "Detectar 4 fallos y mejorarlo", "Pasar JavaFX", "Más campos"], a: "Detectar 4 fallos y mejorarlo", f: "La auditoría de usabilidad busca identificar puntos críticos para rediseñarlos."},
    {q: "14. Cuatro claves para un formulario bien diseñado:", o: ["Orden/simple/feedback/prevención", "Ocultar errores", "Muchos campos", "Sin validar"], a: "Orden/simple/feedback/prevención", f: "Son los pilares para que el usuario no se pierda ni cometa errores."},
    {q: "15. Tres métricas comunes en evaluación de usabilidad:", o: ["CPU/memoria", "Login/CRUD", "Colores RGB", "Éxito/rapidez/satisfacción"], a: "Éxito/rapidez/satisfacción", f: "Miden la Efectividad, Eficiencia y la parte subjetiva del usuario."},
    {q: "16. ¿Qué mide el porcentaje de tareas realizadas correctamente?", o: ["Clics totales", "Arranque", "Efectividad", "MB informes"], a: "Efectividad", f: "La efectividad se mide por la tasa de éxito en la culminación de tareas."},
    {q: "17. Beneficio de la banca online al mejorar usabilidad:", o: ["Más errores", "Menos fallos + confianza", "Más clics", "Colores oscuros"], a: "Menos fallos + confianza", f: "Una interfaz usable reduce errores críticos y aumenta la fidelidad del cliente."},
    {q: "18. ¿Cómo se mide la facilidad de aprendizaje?", o: ["Primera vs otras veces", "Errores total", "Nota 1-5", "Memoria año"], a: "Primera vs otras", f: "Se compara cuánto tarda un usuario novel frente a uno que ya conoce la herramienta."},
    {q: "19. Mensaje ante login con datos vacíos o incorrectos:", o: ["Silencio", "Mensaje claro específico", "Ocultar campo", "Nueva clave"], a: "Mensaje claro específico", f: "El feedback debe orientar al usuario sobre qué corregir exactamente."},
    {q: "20. ¿Qué librería genera informes y los exporta a PDF?", o: ["iText", "Apache POI", "JasperReports", "BIRT"], a: "JasperReports", f: "Es la solución líder de código abierto para reporting en Java."},
    {q: "21. ¿Extensión del formato editable de informe antes de compilar?", o: [".jasper", ".pdf", ".jrxml", ".jrprint"], a: ".jrxml", f: "El archivo JRXML es el XML de diseño editable en Jaspersoft Studio."},
    {q: "22. ¿Qué tipo de parámetro se pasa a JasperFillManager?", o: ["Línea comandos", "Archivo config", "Variables sistema", "Map"], a: "Map", f: "Se utiliza un objeto Map (clave-valor) para pasar parámetros externos al informe."},
    {q: "23. Pasos generales para crear un informe desde JRXML:", o: ["Compilar/llenar/exportar", "Solo validar", "GUI directa", "Excel primero"], a: "Compilar/llenar/exportar", f: "Es el flujo lógico: .jrxml -> .jasper -> JasperPrint -> PDF."},
    {q: "24. Fuente de datos típica de informes en prácticas:", o: ["XML fijos", "Memoria RAM", "Base datos JDBC", "Web JSON"], a: "Base datos JDBC", f: "Lo habitual es que el informe se nutra de una consulta SQL vía conexión JDBC."},
    {q: "25. ¿Para qué se usan las variables en un JRXML?", o: ["Sumar totales resumen", "Guardar config", "Cambiar idioma", "Cambiar BD"], a: "Sumar totales resumen", f: "Las variables realizan cálculos internos como sumas, promedios o conteos."},
    {q: "26. ¿Qué fuente de datos usa JRResultSetDataSource?", o: ["JDBC directo", "Solo parámetros", "Objetos Java", "XML importado"], a: "JDBC directo", f: "Utiliza un ResultSet proveniente de una consulta JDBC ejecutada previamente."},
    {q: "27. Pruebas adecuadas para detectar datos inválidos de clientes:", o: ["Rendimiento", "Caja negra", "Seguridad", "Carga"], a: "Caja negra", f: "Las pruebas de caja negra validan las entradas y salidas sin mirar el código interno."},
    {q: "28. Problemas que puede provocar la BD durante pruebas:", o: ["Diagrama UML", "Manual largo", "Tabla pasos/resultados", "Solo vídeo"], a: "Tabla pasos/resultados", f: "En el diseño de pruebas se usa una tabla para documentar qué esperamos y qué sucede realmente."},
    {q: "29. Fallos comunes de la BD al simular pruebas:", o: ["Disco lleno", "Sin conexión/restricción", "Internet cortado", "Pantalla negra"], a: "Sin conexión/restricción", f: "Errores de conectividad o violación de integridad referencial son típicos."},
    {q: "30. Pruebas tras modificar la interfaz gráfica:", o: ["Regresión", "Estrés máximo", "Reinstalar", "Navegadores"], a: "Regresión", f: "Las pruebas de regresión aseguran que los cambios no dañaron lo que ya funcionaba."},
    {q: "31. ¿Qué evalúa una prueba de usabilidad en el menú principal?", o: ["Procesador", "Textos/clics/avisos", "Código fuente", "Servidor"], a: "Textos/clics/avisos", f: "Se centra en la interacción: si los textos se entienden y los clics llevan a donde deben."},
    {q: "32. ¿Qué situación representa una prueba de usuario final?", o: ["Instalar JDK", "Tema oscuro", "Cliente + pedido", "Configurar IDE"], a: "Cliente + pedido", f: "Representa un flujo de negocio real realizado por la persona que usará la app."},
    {q: "33. ¿Qué ofrece una prueba de aceptación de usuarios?", o: ["Puntuación 1-5", "Preguntas libres", "50 test", "Llamadas"], a: "Puntuación 1-5", f: "Suelen ser encuestas de satisfacción cuantitativas sobre la experiencia de uso."},
    {q: "34. Diagrama que muestra integración entre capas:", o: ["Clases UML", "Capas GUI/servicio/BD", "Tablas BD", "Archivos"], a: "Capas GUI/servicio/BD", f: "Muestra la arquitectura lógica de cómo se comunican la interfaz, el servicio y los datos."},
    {q: "35. Aspecto de prueba de sistema centrado en la interfaz:", o: ["Teclado modelo", "Carga/navega/funciona", "Altavoces", "Resolución"], a: "Carga/navega/funciona", f: "Verifica que el sistema completo sea estable y funcional desde la UI."},
    {q: "36. Participantes orientativos en una prueba de usabilidad básica:", o: ["Solo profe", "Nadie", "Clientes reales", "2-3 compañeros"], a: "2-3 compañeros", f: "En pruebas de pasillo o informales, 2 o 3 observadores bastan para detectar errores obvios."},
    {q: "37. ¿Qué se compara en una prueba de regresión tras cambios?", o: ["Solo antes", "Resultados + fallos nuevos", "Sin tabla", "Solo humo"], a: "Resultados + fallos nuevos", f: "Se verifica que el resultado sea igual al anterior y que no hayan aparecido bugs nuevos."},
    {q: "38. Organización del código AppNotas para estructura clara:", o: ["Paquetes modelo/DAO/GUI", "Todo junto", "Sin Maven", "Una clase"], a: "Paquetes", f: "Es el estándar para separar responsabilidades (Modelo de datos, Acceso a datos y Vista)."},
    {q: "39. Menú típico de ventana principal de AppNotas:", o: ["Solo salir", "Archivo + notas", "Vacío", "Sin menú"], a: "Archivo + notas", f: "Suele contener las opciones de gestión documental y las acciones principales de la app."},
    {q: "40. Forma más sencilla de probar el DAO inicialmente:", o: ["JUnit avanzado", "Con Jasper", "Main simple", "Sin probar"], a: "Main simple", f: "Un método main que instancie el DAO y haga un 'insert' o 'list' es la prueba más rápida de integración."},
    {q: "41. ¿Por qué se eligen ciertos casos de regresión y no todos?", o: ["Todos nuevos", "Los afectados + razón", "Solo básico", "Sin explicar"], a: "Los afectados", f: "Por economía de tiempo, se priorizan las áreas que tienen más probabilidad de haber sido impactadas por el cambio."}
    ]
  }
];

const mappedQuestions = [];
let globalIndex = 316;

rawSections.forEach(section => {
  section.data.forEach((q, i) => {
    let opts = q.o.map((text, idx) => ({
      id: String.fromCharCode(97 + idx),
      text: text
    }));
    
    let correctOpt = opts.find(opt => q.a.includes(opt.text) || opt.text.includes(q.a));
    let correctId = correctOpt ? correctOpt.id : 'a';
    
    mappedQuestions.push({
      id: "int-q" + String(globalIndex).padStart(3, '0'),
      subjectId: 'interfaces',
      moduleId: section.moduleId,
      question: q.q,
      options: opts,
      correctOptionId: correctId,
      explanation: q.f,
      optionExplanations: {} 
    });
    
    globalIndex++;
  });
});

const existing = JSON.parse(fs.readFileSync('data/questions.json', 'utf8'));
const combined = existing.concat(mappedQuestions);

fs.writeFileSync('data/questions.json', JSON.stringify(combined, null, 2));

console.log('Successfully added ' + mappedQuestions.length + ' interface questions part 3. Total: ' + combined.length);
